# Generated by Django 4.1.7 on 2023-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postupadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.CharField(max_length=15, null=True)),
                ('bio', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(null=True, upload_to='userimage/')),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
    ]
