# Generated by Django 4.1.7 on 2023-05-31 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='userImage/')),
                ('blogHead', models.CharField(max_length=200)),
                ('blogBody', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=30)),
                ('time', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commen.user')),
            ],
            options={
                'db_table': 'poste',
            },
        ),
    ]
